### ISSUE TITLE
How do you preselect checkboxes in a checkbox_list?

### ISSUE THREAD

**Issue by pdmwu** [wpmetabox/docs#24]
The docs do not give any indication on how to preselect one or more checkboxes by default when loading the page initially.

https://docs.metabox.io/fields/checkbox-list/

How can this be done programmatically?

**Comment by rilwis** [comment]
It's the `std` parameter. Please see this docs for details:

https://docs.metabox.io/field-settings/

**Comment by pdmwu** [comment]
I have seen the 'std' field. It is not clear to me how it works with checkbox_list

No example is given. Can you tell me how to select "key2" (or "key1" and "key2") in the page edit screen?

```
array(
    'name'            => 'My field)',
    'id'              => 'mainarea',
    'type'            => 'select',
    // Array of 'value' => 'Label' pairs
    'options'         => array(
        'key1' => 'Value 1',
        'key2' => 'Value 2',
    ),
    // Allow to select multiple value?
    'multiple'        => false,
    // Placeholder text
    'placeholder'     => 'nothing selected',
    // Display "Select All / None" button?
    'select_all_none' => false,
),					
```

**Comment by rilwis** [comment]
Please set:

```php
'std' => ['key1'],
```

Or if you want to preselect 2 fields:

```php
'std' => ['key1', 'key2'],
```
