### ISSUE TITLE
Add InnerBlocks possibility to Metabox Blocks extension

### ISSUE THREAD

**Issue by migumuno** [wpmetabox/docs#26]
Hi!

I think that it's a good idea to add the possibility to include [InnerBlocks](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inner-blocks) to Metabox Gutenberg Blocks.

Thank you so much!

**Comment by rilwis** [comment]
Thanks. I'll check it out.

PS: This is the repo for the documentation. So I'll close this ticket. If you have other suggestions, please let us know in the [main repo](https://github.com/wpmetabox/meta-box), or in the [support forum](https://metabox.io/support/).
