### ISSUE TITLE
rwmb_the_value() dont work in the field Video

### ISSUE THREAD

**Issue by campusboy87** [wpmetabox/docs#4]
Hello! I check the performance of this code from [this page](https://github.com/wpmetabox/docs/blob/master/_docs/fields/video.md):

`rwmb_the_value( $field_id );`

But there is an error:
![screenshot-wp-test ru-2018-01-26-17-25-09-389](https://user-images.githubusercontent.com/20075333/35444010-19dba48e-02be-11e8-92e8-691165b7aff0.png)

All examples in the Video field documentation work, except this.

In the post is an empty list of two li elements (I have 2 videos).

**Comment by rilwis** [comment]
Thanks for your feedback. It's fixed in https://github.com/wpmetabox/meta-box/commit/4dff0cd5755e7675f27c8870204288727d517653
