### ISSUE TITLE
Doc - Text List

### ISSUE THREAD

**Issue by campusboy87** [wpmetabox/docs#5]
Hello. There was an inaccuracy in the documentation for the [Text List](https://github.com/wpmetabox/docs/blob/master/_docs/fields/text-list.md) field:

> This field always stored the value as a serialized indexed array in a single row in the database. Each value in the array is the value of input defined in the options setting.

But the data of the cloned field is stored in this way.  For a normal Text List field, the data is stored as follows:

![](http://wp-kama.ru/wp-content/uploads/2018/02/field-Text-List-DB-simple.png)

More.

> You are able to select multiple values from the predefined list.

Does the option ``datalist`` mean? If "Yes", then how correctly is it used in the Text List field? I could not get.

**Comment by rilwis** [comment]
@campusboy87 Thanks for your comment. I've fixed that in the docs.
